json.id home.id
json.description home.description
json.year_build home.year_build
json.square_feet home.square_feet
json.bedrooms home.bedrooms
json.bathrooms home.square_feet
json.floors home.floors
json.availability home.availability
json.address home.address
json.price home.price
